#!/bin/bash
 echo "YEAH!"
while [ 1 ];
do
    count=`curl -s "github.com/NewChallenger/NewChallenger/blob/master/README" | grep -c "N"`

    if [ "$count" != "0" ]
    then
       echo "YEAH!"
       exit 0   
    fi
echo $count
    sleep 1   
done
